server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:7432/main
    username: main
    password: main
  sql:
    init:
      mode: always

date:
  pattern: yyyy-MM-dd HH:mm:ss

stats-server:
  url: http://localhost:9090