server:
  port: 9090

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6642/stats
    username: stats
    password: stats
  sql:
    init:
      mode: always
  h2:
    console.enabled: true

main-service:
  url: http://localhost:8080